### ISSUE TITLE
Index out of range when add modules to beacon with mod "Beacon Rebalance"

### ISSUE THREAD

**Issue by EilRoviSoft** [DanielKote/Foreman2#119]
Got this exception after I tried to add modules (7th module out of 8)
![image](https://github.com/user-attachments/assets/8201a80f-fa9b-4173-bcdd-17cd6fcaea14)

**Comment by EilRoviSoft** [comment]
This is detailed info of exception:

```See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Foreman.BeaconElement.Draw(Graphics graphics, NodeDrawingStyle style) in D:\software\Factorios\Foreman 2\Foreman\ProductionGraphView\Elements\BeaconElement.cs:line 73
   at Foreman.GraphElement.Paint(Graphics graphics, NodeDrawingStyle style) in D:\software\Factorios\Foreman 2\Foreman\ProductionGraphView\Elements\GraphElement.cs:line 107
   at Foreman.GraphElement.Paint(Graphics graphics, NodeDrawingStyle style) in D:\software\Factorios\Foreman 2\Foreman\ProductionGraphView\Elements\GraphElement.cs:line 110
   at Foreman.ProductionGraphViewer.Paint(Graphics graphics, Boolean FullGraph) in D:\software\Factorios\Foreman 2\Foreman\ProductionGraphView\ProductionGraphViewer.cs:line 664
   at Foreman.ProductionGraphViewer.OnPaint(PaintEventArgs e) in D:\software\Factorios\Foreman 2\Foreman\ProductionGraphView\ProductionGraphViewer.cs:line 610
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9277.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Foreman
    Assembly Version: 2.2.15.2
    Win32 Version: 2.2.15.2
    CodeBase: file:///D:/applications/foreman-2.0/Foreman%202.2.16.1/Foreman.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9251.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9261.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9277.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.1.20720
    CodeBase: file:///D:/applications/foreman-2.0/Foreman%202.2.16.1/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Google.OrTools
    Assembly Version: 9.1.9490.0
    Win32 Version: 9.1.9490.0
    CodeBase: file:///D:/applications/foreman-2.0/Foreman%202.2.16.1/Google.OrTools.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```

**Comment by EilRoviSoft** [comment]
To be more precise: this exception appears with high level of details when I add more than 6 modules.

As timed fix I forked your repository and just commented render of modules more than 6.

![image](https://github.com/user-attachments/assets/eb3929c5-6fb1-4a7a-a775-0629d5d0f265)

**Comment by Olipro** [comment]
Please grab this snapshot release: https://github.com/DanielKote/Foreman2/actions/runs/25997271125/artifacts/7044385625

Let me know if it still has the issue.

**Comment by EilRoviSoft** [comment]
I have already fixed this issue on my fork but I'll try snapshot

**Comment by EilRoviSoft** [comment]
Tried snapshot but still getting the same error. My solution was to change indexing from `(x * 7) + y` to `(x * 4) + y`. Current implementation clearly have indexing error.

<img width="2232" height="1188" alt="Snapshot" src="https://github.com/user-attachments/assets/dc75942e-1c8a-4359-86ba-88164e73756b" />

<img width="2560" height="1528" alt="My implementation" src="https://github.com/user-attachments/assets/2a0bba93-5202-4eff-91fc-962059fb35e6" />

**Comment by Olipro** [comment]
Thanks for the information. I'll merge a PR imminently. If you'd like to use the snapshot, you can grab it from the bottom of this page: https://github.com/DanielKote/Foreman2/actions/runs/26073441663
